### ISSUE TITLE
Wifi Access Point wird nicht geöffnet

### ISSUE THREAD

**Issue by viper-666** [tobiasfaust/HomeStatusDisplay#3]
In der Original HSD Firmware wird beim ersten Start ein Wifi Access Point mit dem Namen HomeStatusDisplay geöffnet mit dem man sich verbindet um seine WIFI Daten einzutragen.
Leider funktioniert dies mit deiner Version nicht (zumindest beim ESP8266 Board). Es wird versucht die Daten aus dem Flash zu lesen:
`Initializing config.
Mounted file system.
Reading config file /config.json
File size is 248 bytes
Main config data successfully parsed.
JSON length is 248
  • version         : 0.7@Testing
  • host            : HomeStatusDisplay
  • guiUser         : admin
  • guiPass         : not shown
  • mqttServer      : test.mosquitto.org
  • mqttServerUser  : 
  • mqttServerPass  : not shown
  • mqttStatusTopic : 
  • mqttTestTopic   : 
  • mqttWillTopic   : 
  • ledCount        : 0
  • ledPin          : 0
  • ledBrightness   : 50

Config data is complete.
Deleting color mapping config data.
Reading config file /colormapping.json
File size is 2 bytes
Color mapping config data successfully parsed.
JSON length is 2

Deleting device mapping config data.
Reading config file /devicemapping.json
File size is 2 bytes
Device mapping config data successfully parsed.
JSON length is 2

Starting WebServer.
WiFi credentials loaded from EEPROM
Try to connect...
Starting Wifi connection to ��������������������������������
Waiting 0/120sec`
Und obwohl auf dem ESP8266 schon diese Daten waren scheinen diese beim Flashen (mit VSCode) nicht mehr vorhanden zu sein.
Auch nachdem ich mit esptool den Flash komplett gelöscht habe und danach alles noch einmal mit VSCode geflashed habe kommt kein Access Point.

Ich habe zum Quervergleich noch einmal das Original von MTJoker geflashed und der Access Point wurde geöffnet.

**Comment by tobiasfaust** [comment]
das ist auch korrekt so, den Accesspoint habe ich extra ausgebaut, der web-installer ist der einzige weg den ESP zu initialisieren. Dieser ist einfacher zu bedienen als die nutzung über einen AP.
Die Wifi Zugangsdaten werden im NVS bzw eeprom abgelegt. Beim Update über OTA bleiben die Zugangsdaten gespeichert.

**Comment by viper-666** [comment]
OK, heißt bei dem Webinstaller kann man die Zugangsdaten eintragen?
Ich konnte den auf Linux leider nicht nutzen (siehe anderes Issue).

**Comment by viper-666** [comment]
Fehler beim Webinstaller gefunden.
