### ISSUE TITLE
Webinstaller funktioniert nicht unter Linux

### ISSUE THREAD

**Issue by viper-666** [tobiasfaust/HomeStatusDisplay#4]
Der Webinstaller funktioniert nicht unter Linux, anscheinend kann er nichts mit den Port /dev/ttyUSB0 anfangen.

**Comment by tobiasfaust** [comment]
laut doku vom ESP-Web-Tools:

Web Serial is available in Google Chrome and Microsoft Edge browsers. Android support should be possible but has not been implemented yet.


probier mal den Chrome Browser

**Comment by viper-666** [comment]
Ok, werde mal einen anderen Browser versuchen. Hatte das in Opera versucht, der basiert zwar auf Chrome aber ist wahrscheinlich nicht 100%tig compatible.

**Comment by viper-666** [comment]
So, habe jetzt alles Probiert, habe den Chrome Browser in Linux installiert, habe Windows gebootet und dort unter Edge versucht überall das gleiche. Es öffnet sich folgende Webseite:
![WebInstaller](https://github.com/user-attachments/assets/ec8cad30-0a57-4e1d-9244-c80231fea26c)
Aber im Feld kann man nichts auswählen obwohl der Port erkannt wurde.
Dann habe ich auf den Link powered by ESP Web Tools geklickt und auf deren Seite konnte ich dann auf Connect klicken und ESP-Tools auf dem ESP8266 installieren, es wurde auch das WIFI abgefragt.
Anschließend habe ich mit deren OTA Update die Firmware auf den ESP geflashed.
Aber nach dem Start funktionierte es wieder nicht, auf der Seriellen Console konnte man dann das gleiche lesen wie auf meinem anderen Issue.
Wie bekomme ich die Wifi Zugangsdaten auf den ESP?

**Comment by tobiasfaust** [comment]
Hi,
ein bild sagt 1000 worte..... dein problem hat nichts mit dem serialport zu tun. Irgendwie bist du auf der falschen seite oder das Javascript funktioniert nicht korrekt
Hier musst du hin: https://tobiasfaust.github.io/HomeStatusDisplay/
und dann sieht es so aus, deine Überschrift "Welcome to the home web installer!" passt schon nicht
![image](https://github.com/user-attachments/assets/197a5ea1-962d-404b-a9d9-b5b48eaf8b85)

Die Wifi Zugangsdaten kann man setzen, wenn man auf "Install" klickt. In einem der folgenden Fenster erscheint dann "Change Wi-Fi".
Hier hatte ich für mein anderes Projekt schon eine Wiki Seite erstellt:
https://github.com/tobiasfaust/SolaxModbusGateway/wiki/start-and-integration-into-locale-wifi

Ich habe es auch auf einem Debian mit Chromium probiert..... funktioniert

**Comment by viper-666** [comment]
So einen Schritt weiter, ich hatte den Webinstaller runter geladen und im Verzeichnis ausgefüht.
Habe jetzt heraus gefunden, dass ich auf den Link unter About klicken muss.
Aber dann kann ich zwar eine Version auswählen, auf Install klicken, den Port auswählen und er flashed die Firmware.
Bleibt dann aber hängen bei:
![HSD_V15](https://github.com/user-attachments/assets/6e639b2d-98d8-410c-96d4-ef1dd3387c35)
Das ist dann genau die Stelle wo er auf der Seriellen Console ausgibt, dass nach Wifi Daten sucht und nicht connecten kann.
Ich kann mich danach auch nicht mehr mit dem Webinstaller mit dem Port verbinden um eine andere Version aufzuspielen. Er schreibt dann connecting und bleibt genauso hängen wie die bei dem "Wraping up" screen.
Eventuell musst du ein wait commando in der Loop eingeben, damit er eine chance hat sich zu verbinden.
Du hast es ja jetzt so programmiert, dass wenn er sich nicht mit WIFI verbinden kann resetet und neu startet.

**Comment by viper-666** [comment]
Ach probiert habe ich Build 13, 14 und die neue V15.

**Comment by viper-666** [comment]
Gerade erst deine Antwort gesehen, die Seite wo man sein WIFI auswählen kann erscheint bei mir leider nicht.
Die kam als ich es gestern über den Originalen ESP Web Tools installiert habe.
Ich werde den ESP jetzt noch mal komplett platt machen, eventuell hat der Webinstaller von ESP Web Tool irgenwas im Flash geschrieben, dass diese Seite jetzt  nicht mehr kommt.
Melde nich in ein paar minuten ob es funktioniert hat.

**Comment by viper-666** [comment]
Hat leider nicht geholfen, hänge wieder bei der Seite "Wraping up" und WIFI wurde nicht abgefragt.

**Comment by tobiasfaust** [comment]
Hast du während des wrapping Up am esp auf den Boot Button gedrückt? Normalerweise wartet er bis der esp in den Download-Mode gegangen ist. Oftmals muss man hierzu eben den Button drücken.
Für mehr debugmeldunge aktiviere mal im browser die entwicklertools und schaue dir die Konsole an.

erst nach dem Flash werden wifi Daten abgefragt

**Comment by viper-666** [comment]
Das ist ein ESP8266 wo der USB-Anschluss dran ist, der hat keinen Boot Button,
Und das Flashen der Firmware hat er durchgeführt und danach neu gebootet aber dann geht es nicht weiter weil dann die "Wraping up" Meldung nicht weg geht.
Ich vermute stark weil der ESP andauernd neu bootet, kann ich dann sehen wenn ich mich per Serieller Konsole verbinde.
Diese Ausgabe kommt dann fortlaufend:
`
Initializing config.
Mounted file system.
Reading config file /config.json
File size is 248 bytes
Main config data successfully parsed.
JSON length is 248
• version : 0.7@Testing
• host : HomeStatusDisplay
• guiUser : admin
• guiPass : not shown
• mqttServer : test.mosquitto.org
• mqttServerUser :
• mqttServerPass : not shown
• mqttStatusTopic :
• mqttTestTopic :
• mqttWillTopic :
• ledCount : 0
• ledPin : 0
• ledBrightness : 50

Config data is complete.
Deleting color mapping config data.
Reading config file /colormapping.json
File size is 2 bytes
Color mapping config data successfully parsed.
JSON length is 2

Deleting device mapping config data.
Reading config file /devicemapping.json
File size is 2 bytes
Device mapping config data successfully parsed.
JSON length is 2

Starting WebServer.
WiFi credentials loaded from EEPROM
Try to connect...
Starting Wifi connection to ��������������������������������
Waiting 0/120sec
...
und am Ende 120/120sec
rebooting
`
Und das dauert keine 120s vielleicht max. 2s.

**Comment by tobiasfaust** [comment]
ok, bin teste aktuell nur mit einem ESP32, mit ESP8266 muss ich noch durchtesten. Kommt nächste Woche. Dieser fork konzentriert sich ja auf ESP32. Für ESP8266 könnte man auch das original verwenden ;)

**Comment by viper-666** [comment]
Ok, danke, dann warte ich bis nächste Woche.
Hier die Ausgabe der Console des Browsers während des Flashen, nach dem letztem Schritt passiert nichts mehr.
Auch nicht wenn ich den ESP mittels Reset resette:
![HSD-Serial](https://github.com/user-attachments/assets/69022b22-b1c6-4fde-9211-d60cdb8abfd9)

**Comment by viper-666** [comment]
Ich konnte den Fehler finden, siehe Pull Request.

**Comment by tobiasfaust** [comment]
Ich habe den Fehler heute auch schon gefunden und in meiner ImprovWifi Library angepasst. Will ich morgen aber nochmal ausgiebigst testen.
wenn du den HSD über gitpod einmal selbst kompilierst kannst du es testen, würde erst morgen einen offiziellen neuen Build erstellen

**Comment by viper-666** [comment]
Ich habe leider keinen zweiten ESP8266 ich habe noch ein paar ESP01 Module, da schaue ich heute Abend mal wie ich die flashen kann.
Bei den ESP8266 welcher in den Bilderrahmen eingebaut ist habe ich gestern 30min gebraucht alle LESs und Geräte in der Weboberfläche einzugeben. Das wäre alles weg wenn ich den noch einmal über den Webflasher mit der neuen Firmware bespiele.
Was ichj aber festgestellt habe ist, dass im normalen Betrieb "improvSerial.loop();" zu selten aufgerufen wird. Ich habe bis zu 10 Versuche gebraucht bis bei dem Webflasher "Configure Wifi" angezeigt wurde.
Inwieweit das interessant ist? Man kann nach dem ersten Einrichten ja komfortabel und ohne Daten zu verlieren über den OTA update neue FW flashen.
Wäre eventuell interessant wenn man das WLAN geändert hat.

**Comment by viper-666** [comment]
Ach und hast du vielleicht eine Anleitung wie Gitpod funktioniert?
Habe das bei mir auch als Plugin installiert und mit Github verknüft aber wenn ich dich richtig verstehe, kann Gitpod automatisch neue Releases erstellen. Das klappt bei mir nicht...

**Comment by tobiasfaust** [comment]
Im aktuellen Build 18 sollte alles jetzt funktionieren. Auch ein häufigerer Aufruf des Loops der ImprovSerial ist dort mit enthalten.
Hier habe ich in meinem parallelprojekt schon eine Anleitung hinterlegt: https://github.com/tobiasfaust/SolaxModbusGateway/wiki/build-with-gitpod

Und ja, hast du es einmal installiert, sollte man mittels OTA aktualisieren.

**Comment by viper-666** [comment]
So, war doch kein ESP01 sondern ein ESP201.
Konnte aber deine Änderung testen und es hat funktioniert. Nach dem flashen und konnte sich der Webinstaller über die improv Schnittstelle verbinden und ich konnte die WIFI Zugangsdaten vergeben.
Tolle Arbeit, vielen Dank!!!

**Comment by viper-666** [comment]
Damit ist dieses Issue gefixt.
